import { expect, test } from '@playwright/test'

test('REPLAY: thinking streams separately, survives refresh without duplication, folds and stops', async ({ page }) => {
  test.setTimeout(60_000)
  const errors: string[] = []
  const external: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    if (request.url().includes('wb10.invalid')) external.push(request.url())
  })
  await page.goto('/')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-synthetic-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯 WB10_BROWSER')
  await page.getByRole('button', { name: '发送消息' }).click()
  let panel = page.getByRole('region', { name: '思考过程' })
  await expect(panel).toContainText('REPLAY 思考第一段。')
  await expect(panel.getByRole('button')).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.provisional')).toHaveCount(0)
  await panel.getByRole('button').click()
  await expect(panel.locator('.reasoning-content')).toHaveCount(0)
  await panel.getByRole('button').click()
  await expect(panel).toContainText('REPLAY 思考第二段。')
  await page.reload()
  panel = page.getByRole('region', { name: '思考过程' })
  await expect(panel.getByRole('button')).toHaveAttribute('aria-expanded', 'true')
  await expect(panel.locator('.reasoning-content')).toContainText('REPLAY 思考第一段。')
  await expect(panel.locator('.reasoning-content')).toContainText('REPLAY 思考第二段。')
  expect((await panel.innerText()).match(/REPLAY 思考第一段。/g)).toHaveLength(1)
  expect((await panel.innerText()).match(/REPLAY 思考第二段。/g)).toHaveLength(1)
  await expect(panel).toContainText('[图片已隐藏：隐藏像素]')
  await page.screenshot({ path: 'test-results/wb10-thinking-running.png', fullPage: true })
  await expect(page.getByText('REPLAY 正文独立完整。', { exact: true })).toBeVisible({ timeout: 15_000 })
  await expect(panel.getByRole('button')).toHaveAttribute('aria-expanded', 'false')
  await panel.getByRole('button').click()
  await expect(panel).toContainText('REPLAY 思考第二段。')
  await page.reload()
  await expect(panel.getByRole('button')).toHaveAttribute('aria-expanded', 'false')
  await panel.getByRole('button').click()
  expect((await panel.innerText()).match(/REPLAY 思考第一段。/g)).toHaveLength(1)
  await page.screenshot({ path: 'test-results/wb10-thinking-complete.png', fullPage: true })
  expect(await page.evaluate(() => (window as Window & { __wb10_xss?: boolean }).__wb10_xss)).toBeUndefined()
  expect(external).toEqual([])

  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯 WB10_BROWSER_STOP')
  await page.getByRole('button', { name: '发送消息' }).click()
  const stopped = page.locator('.turn').last().getByRole('region', { name: '思考过程' })
  await expect(stopped).toContainText('REPLAY 思考第一段。')
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(stopped).toContainText('思考已中断')
  await stopped.getByRole('button').click()
  await expect(stopped).toContainText('REPLAY 思考第一段。')
  expect(errors).toEqual([])
})
