import { expect, test } from '@playwright/test'
import { Buffer } from 'node:buffer'

test('REPLAY: private accounts, persistent conversations, history, cancellation and deletion', async ({ page, context, browser }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  const username = `browser-user-${Date.now()}`
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '登录工作台' })).toBeVisible()
  await page.screenshot({ path: 'test-results/wb01-login.png', fullPage: true })
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-synthetic-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('button', { name: '账号管理' })).toBeVisible()
  const cookies = await context.cookies()
  expect(cookies.find(c => c.name === '__Host-hwops')).toMatchObject({ secure: true, httpOnly: true, sameSite: 'Strict' })
  await page.getByRole('button', { name: '账号管理' }).click()
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill(username)
  await page.getByRole('textbox', { name: '初始密码' }).fill('wb01-browser-password')
  await page.getByRole('button', { name: '创建账号' }).click()
  await expect(page.locator('.users').getByText(username, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '退出', exact: true }).click()
  await expect(page.getByRole('heading', { name: '登录工作台' })).toBeVisible()
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill(username)
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-browser-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '账号管理' })).toHaveCount(0)
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯表示什么？')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.getByText('合成手册说明：蓝灯表示维护模式。', { exact: true })).toBeVisible()
  await expect(page.getByText('REPLAY · 确定性回放', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/wb01-chat-desktop.png', fullPage: true })
  await page.getByRole('button', { name: /WB01 合成运维手册/ }).click()
  await expect(page.getByRole('dialog', { name: '引用原文' })).toContainText('合成测试设备的蓝灯表示维护模式。本资料为浏览器验收专用。')
  await page.screenshot({ path: 'test-results/wb01-citation.png', fullPage: true })
  await page.getByRole('button', { name: '关闭引用' }).click()
  await page.getByRole('button', { name: '重命名会话', exact: true }).click()
  await page.getByRole('textbox', { name: '会话标题' }).fill('蓝灯排查记录')
  await page.getByRole('button', { name: '保存标题' }).click()
  await expect(page.locator('.current-title')).toHaveText('蓝灯排查记录')
  const firstURL = page.url()
  await page.reload()
  await expect(page.getByText('合成手册说明：蓝灯表示维护模式。', { exact: true })).toBeVisible()
  await expect(page.locator('.current-title')).toHaveText('蓝灯排查记录')
  // A fresh browser context authenticates independently and sees the same DB history.
  const secondContext = await browser.newContext()
  const secondPage = await secondContext.newPage()
  await secondPage.goto(firstURL)
  await secondPage.getByRole('textbox', { name: '用户名', exact: true }).fill(username)
  await secondPage.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-browser-password')
  await secondPage.getByRole('button', { name: '登录', exact: true }).click()
  await expect(secondPage.locator('.current-title')).toHaveText('蓝灯排查记录')
  await expect(secondPage.getByText('合成手册说明：蓝灯表示维护模式。', { exact: true })).toBeVisible()
  await secondContext.close()
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('保留第一会话输入')
  await page.getByRole('button', { name: '新建会话', exact: false }).click()
  await expect(page.locator('.current-title')).toHaveText('新会话')
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯 WB02_BROWSER_BLOCK')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.getByRole('button', { name: '停止', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('处理中保留的下一条输入')
  await expect(page.getByRole('button', { name: '发送消息' })).toBeDisabled()
  await page.getByRole('button', { name: '停止', exact: true }).click()
  await expect(page.getByText('本轮已停止。', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toHaveValue('处理中保留的下一条输入')
  await page.getByRole('button', { name: '重试这一轮' }).click()
  await expect(page.locator('.turn')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '停止', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除会话', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '删除会话' })).toContainText('不可恢复')
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '删除会话' })).toHaveCount(0)
  await page.getByRole('textbox', { name: '搜索历史' }).fill('蓝灯排查')
  await expect(page.getByRole('navigation', { name: '会话列表' }).getByRole('button')).toHaveCount(1)
  await page.getByRole('button', { name: '蓝灯排查记录', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toHaveValue('保留第一会话输入')
  await expect(page.locator('.turn')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/wb02-persistent-history.png', fullPage: true })
  await page.getByRole('button', { name: '新建会话', exact: false }).click()
  await expect(page.locator('.current-title')).toHaveText('新会话')
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯 WB05_BROWSER_STREAM')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.getByText('生成中草稿', { exact: true })).toBeVisible()
  await expect(page.locator('.provisional')).toContainText('浏览器真实')
  await page.screenshot({ path: 'test-results/wb05-live-draft.png', fullPage: true })
  await expect(page.getByText('浏览器真实增量正文。', { exact: true })).toBeVisible()
  await expect(page.getByText('生成中草稿', { exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/wb01-chat-mobile.png', fullPage: true })
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
  expect(errors).toEqual([])
})

test('REPLAY: attachment choose, paste, drop, parse status and source preview', async ({ page }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-synthetic-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeVisible()

  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')
  await page.locator('input[type=file]').setInputFiles({
    name: 'selected.png', mimeType: 'image/png', buffer: png,
  })
  await expect(page.locator('.attachment-draft').filter({ hasText: 'selected.png' })).toContainText('已就绪')
  await page.getByRole('button', { name: 'selected.png', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '附件 selected.png' })).toBeVisible()
  await expect(page.locator('.attachment-original')).toBeVisible()
  await page.getByRole('button', { name: '关闭附件' }).click()

  await page.getByRole('textbox', { name: '消息', exact: true }).evaluate((element, encoded) => {
    const bytes = Uint8Array.from(atob(encoded), value => value.charCodeAt(0))
    const transfer = new DataTransfer()
    transfer.items.add(new File([bytes], 'pasted.png', { type: 'image/png' }))
    element.dispatchEvent(new ClipboardEvent('paste', {
      bubbles: true, cancelable: true, clipboardData: transfer,
    }))
  }, png.toString('base64'))
  await expect(page.locator('.attachment-draft').filter({ hasText: 'pasted.png' })).toContainText('已就绪')

  await page.locator('.composer').evaluate((element) => {
    const transfer = new DataTransfer()
    transfer.items.add(new File(['%PDF-FAKE-WB04'], 'manual.pdf', { type: 'application/pdf' }))
    transfer.items.add(new File(['line one\nline two ERROR\n'], 'device.log', { type: 'text/plain' }))
    element.dispatchEvent(new DragEvent('drop', {
      bubbles: true, cancelable: true, dataTransfer: transfer,
    }))
  })
  await expect(page.locator('.attachment-draft').filter({ hasText: 'manual.pdf' })).toContainText('部分可用')
  await expect(page.locator('.attachment-draft').filter({ hasText: 'device.log' })).toContainText('已就绪')
  await page.screenshot({ path: 'test-results/wb04-attachment-drafts.png', fullPage: true })

  await page.getByRole('textbox', { name: '消息', exact: true }).fill('蓝灯表示什么？')
  await page.getByRole('button', { name: '发送消息' }).click()
  await expect(page.getByText('合成手册说明：蓝灯表示维护模式。', { exact: true })).toBeVisible()
  for (const name of ['selected.png', 'pasted.png', 'manual.pdf', 'device.log']) {
    await expect(page.locator('.message-attachments').getByRole('button', { name: new RegExp(name) })).toBeVisible()
  }
  await page.locator('.message-attachments').getByRole('button', { name: /device\.log/ }).click()
  const logDrawer = page.getByRole('dialog', { name: '附件 device.log' })
  await expect(logDrawer).toContainText('第 1–2 行')
  await expect(logDrawer.locator('pre')).toContainText('line two ERROR')
  await page.getByRole('button', { name: '关闭附件' }).click()
  await page.locator('.message-attachments').getByRole('button', { name: /manual\.pdf/ }).click()
  const pdfDrawer = page.getByRole('dialog', { name: '附件 manual.pdf' })
  await expect(pdfDrawer).toContainText('第 2 页')
  await expect(pdfDrawer.locator('table')).toContainText('errors')
  await page.screenshot({ path: 'test-results/wb04-pdf-source.png', fullPage: true })
  await page.getByRole('button', { name: '关闭附件' }).click()
  expect(errors).toEqual([])
})

test('ACTUAL SANDBOX + REPLAY MODEL: automatic Python analysis renders output and artifacts', async ({ page }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-synthetic-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeVisible()
  await page.locator('input[type=file]').setInputFiles({
    name: 'browser-events.csv',
    mimeType: 'text/plain',
    buffer: Buffer.from('category,duration_ms\nstorage,120\nnetwork,80\nstorage,180\npower,40\n'),
  })
  await expect(page.locator('.attachment-draft').filter({ hasText: 'browser-events.csv' })).toContainText('已就绪')
  await page.getByRole('textbox', { name: '消息', exact: true }).fill('分析附件 WB06_BROWSER_ANALYSIS')
  await page.getByRole('button', { name: '发送消息' }).click()
  const execution = page.getByLabel('Python 执行记录')
  await expect(execution).toBeVisible()
  await expect(execution).toContainText('/work/output/browser-chart.png')
  await expect(page.getByText('浏览器实际执行完成，共统计 4 条记录并生成 CSV 与柱状图。', { exact: true })).toBeVisible()
  await expect(execution.getByText('browser-summary.csv', { exact: true })).toBeVisible()
  await expect(execution.getByText('browser-chart.png', { exact: true })).toBeVisible()
  await expect(execution.locator('img')).toBeVisible()
  await page.screenshot({ path: 'test-results/wb06-python-artifacts.png', fullPage: true })
  expect(errors).toEqual([])
})

test('REPLAY: safe Markdown, long content, keyboard submission and expired session', async ({ page, browser }) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  const externalRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    if (request.url().includes('wb07.invalid')) externalRequests.push(request.url())
  })
  await page.goto('/')
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('wb01-synthetic-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  const message = page.getByRole('textbox', { name: '消息', exact: true })
  await expect(message).toBeVisible()

  const longName = `${'very-long-diagnostic-file-name-'.repeat(6)}final.log`
  await page.locator('input[type=file]').setInputFiles({
    name: longName,
    mimeType: 'text/plain',
    buffer: Buffer.from('timestamp level component message\n2026-10-04 ERROR storage synthetic\n'),
  })
  await expect(page.locator('.attachment-draft').filter({ hasText: longName })).toContainText('已就绪')
  const question = `蓝灯 WB07_BROWSER_SECURITY ${'超长问题内容'.repeat(180)}`
  await message.fill(question)
  await message.press('Shift+Enter')
  await expect(message).toHaveValue(`${question}\n`)
  await message.press('Enter')

  const turn = page.locator('.turn').last()
  await expect(turn.getByText('安全渲染检查', { exact: true })).toBeVisible()
  await expect(turn.getByText('[图片已隐藏：远程像素]', { exact: true })).toBeVisible()
  await expect(turn.getByText('外部链接', { exact: true })).toBeVisible()
  await expect(turn.locator('img[src^="http"]')).toHaveCount(0)
  await expect(turn.locator('a[href^="http"]')).toHaveCount(0)
  await expect(turn.locator('pre')).toContainText('LONG_CODE_')
  expect(await page.evaluate(() => (window as Window & { __wb07_xss?: boolean }).__wb07_xss)).toBeUndefined()
  expect(externalRequests).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await turn.locator('pre').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/wb07-long-safe-content.png', fullPage: true })

  const username = `wb07-expiry-${Date.now()}`
  await page.getByRole('button', { name: '账号管理' }).click()
  await page.getByRole('textbox', { name: '用户名', exact: true }).fill(username)
  await page.getByRole('textbox', { name: '初始密码' }).fill('wb07-old-password')
  await page.getByRole('button', { name: '创建账号' }).click()
  const userRow = page.locator('.user-row').filter({ hasText: username })
  await expect(userRow).toBeVisible()

  const userContext = await browser.newContext()
  const userPage = await userContext.newPage()
  await userPage.goto('/')
  await userPage.getByRole('textbox', { name: '用户名', exact: true }).fill(username)
  await userPage.getByRole('textbox', { name: '密码', exact: true }).fill('wb07-old-password')
  await userPage.getByRole('button', { name: '登录', exact: true }).click()
  await expect(userPage.getByRole('textbox', { name: '消息', exact: true })).toBeVisible()

  await userRow.getByText('重置密码', { exact: true }).click()
  await userRow.getByRole('textbox', { name: `${username}的新密码` }).fill('wb07-new-password')
  await userRow.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('密码已重置，该账号原有登录状态已撤销。')
  await userPage.getByRole('textbox', { name: '搜索历史' }).fill('触发会话校验')
  await expect(userPage.getByRole('heading', { name: '登录工作台' })).toBeVisible()
  await userContext.close()
  expect(errors).toEqual([])
})
